#-*- mode: org -*-
#+STARTUP: showall

* Tips and Tricks
- Open file on Amazon server described in ~/.ssh/config as awshost1 using tramp:
  C-x C-f /sshx:awshost1:

* Org-mode
  TAB/S-TAB - (un)fold
  M-up/down – move a headline up or down
  M-left/right – promote or demote a headline
  M-RET – insert a new headline
** Lists:
- un- ordered starts with -, * or \*;
- ordered start with number and dot.
- descriptions start with :: here comes description
** Formatting:
   You can make words *bold*, /italic/, _underlined_, =code= and ~verbatim~, and, if you must, +strike-through+.
** todo lists
   S-left/right :: cycle workflow
   C-c C-v – show todos in current document
*** Configuring todo's cycle:
- In the file itself (on the beginning of the file):
  #+TODO: TODO IN-PROGRESS WAITING DONE
- in emacs - config:
  =(setq org-todo-keywords '((sequence "TODO" "IN-PROGRESS" "WAITING" "DONE")))=
** GTD - separate story at [[http://orgmode.org/worg/org-tutorials/org4beginners.html][]

* Prelude + Ergoemacs + Yara's expancions

** Common
   M-a          Alias for M-x.

*** File/buffer/window commands
    C-o          Find file (Open File)
    C-s          Save buffer
    C-x s        Save file (like save-as)
    C-x b        Switch buffer
    C-x k        Kill buffer
    M-3          Delete other windows
    M-2          Delete current window
    M-4          Split window horizontally
    M-S-4        Split window vertically

    C-+          Increase font size(text-scale-increase).
    C--          Decrease font size(text-scale-decrease).

    F9 w         (enable-visual-line-mode)
    F9 i         Arrange emacs window in center (arrange-center)

    F12          Toggle the Emacs menu bar.

** Unknown
   C-x </kbd>   align-regexp
   C-x O        Go back to previous window (the inverse of other-window (C-x o)).

** Editing
   M-e          Kill the previous word(backward-kill-word).
   M-S-6 (M-^)  Join two lines into one(join-line).

   M-</kbd>     Run hippie-expand (a replacement for the default dabbrev-expand).



TODO in Emacs: move to previous/next to M-m / M-,
*** Lines
    F9 d         Duplicate line or region
    C-d          Delete line(s)
    S-RET        Insert an empty line below current and indent it properly (as in most IDEs).
    C-S-RET      Insert an empty line _above_ current and indent it properly (as in most IDEs).
    C-S-up       Move the current line up.
    C-S-down     Move the current line down.

** Shells
   C-x p        Start proced (manage processes form Emacs, works only in Linux).
   C-x m        Start eshell.
   C-x M        Start eshell.
   C-x M-m      Start your default shell.

** Help
   C-h A        Run apropos (search in all Emacs symbols).
   C-x C-b      Open ibuffer (a replacement for the default buffer-list).
   C-x g        Open Magit's status buffer.
   C-=  Run expand-region (incremental text selection).

** Prelude-mode
   C-c o        Open the currently visited file with an external program.
   C-c g        Search in Google for the thing under point (or an interactive query).
   C-c n        Fix indentation in buffer and strip whitespace.
   C-c f        Open recently visitted file.
   C-M-</kbd>   Indent region (if selected) or the entire buffer.
   C-c u        Open URL in your default browser.
   C-c e        Eval a bit of Emacs Lisp code and replace it with its result.
   C-c s        Swap two active windows.
   C-c d        Duplicate the current line (or region).
   C-c r        Rename the currently visited file and buffer.
   C-c t        Open a terminal emulator (ansi-term).
   C-c k        Kill all open buffers except the one you're currently in.
   C-c h        Open Helm (a useful means of navigating your buffers and project files).
** Projectile
   C-c p f      Display a list of all files in the project. With a prefix argument it will clear the cache first.
   C-c p T      Display a list of all test files(specs, features, etc) in the project.
   C-c p g      Run grep on the files in the project.
   C-c p b      Display a list of all project buffers currently open.
   C-c p o      Runs multi-occur on all project buffers currently open.
   C-c p r      Runs interactive query-replace on all files in the projects.
   C-c p i      Invalidates the project cache (if existing).
   C-c p R      Regenerates the projects TAGS file.
   C-c p k      Kills all project buffers.
   C-c p d      Opens the root of the project in dired.
   C-c p e      Shows a list of recently visited project files.
   C-c p a      Runs ack on the project. Requires the presence of ack-and-a-half.
   C-c p l      Runs a standard compilation command for your type of project.
   C-c p p      Runs a standard test command for your type of project.
   C-c p z      Adds the currently visited to the cache.
   C-c p s      Display a list of known projects you can switch to.
   C-c p h     Help on Projectile

** Movement commands
   C-a         Select All
   C-a         Beginning of line
   C-e         End of line
   C-n         Next line (down)
   C-p         Previous line (up)
   C-b         Back (left)
   C-f         Forward (right)
   M-f         Forward a word
   M-b         Back a word
   C-v         Forward a page
   M-v         Back a page
** Edit commands
   C-d         Kill character
   M-d         Kill word
   M-delete    Kill word backwards
   C-_         Undo
   M-_         Redo
** Misc commands
   C-s         Regex search forwards
   C-r         Regex search backwards
   M-%         Query replace
   C-h a       Apropos - search the help for a term
** On/off wrapping:
   M-x visual-line-mode (or menu->Options->Line Wrapping in This Buffer->)

* Evil mode info
- Imenu-mode — меню для навигации по текущему буферу. Обычно языковые режимы emacs автоматически наполняют его позициями в которых определены методы или функции. Отображается меню как пожелаете :) Можно в minibuffer (аналог комадной строки vim), можно в оконном меню а можно в буфере anything.el :) Жутко удобная фича. Расширяется так же просто как anything.
- Speedbar - file management
- Commenting, Yasnippet etc.
