* Dictionary (Description List):
- Abc :: Activity Based Costing
- ABS :: Asset - Backed Securities
- ADR :: American Depository Receipts
- AGM :: Annual General Meeting (of the stockholders)
- AMC :: Asset Management Company
- AML :: Anti-Money Laundering
- APS ::
- ASM :: ATOM Service Manager
- ATOM :: Action and Task Orchestrator Manager
- AWE :: Access Workflow Engine

- BDS :: (Registered) Brokers - Dealers
- BEA :: Business/Enterprise Architecture: official app inventory system of records
- BSA :: Bank Secrecy Act
- BXP :: BNY Mellon eXtreme Platform

- CA  :: Corporate Actions
- CAE :: Client Access Entitlements
- CBI :: Central Bank of Ireland
- CC  :: Control Center (analogous to Eagle)
- CCN :: ?
- CIP :: Customer Identification Program
- COB :: Client Onboarding
- CPU :: ?
- CR  :: Change Request
- CTS :: Client Technology Service
- CSD :: Client Service Delivery
- DNDBW :: Do Not Do Business With list
- DP  :: Digital Pulse
- DRV :: Data Request Vehicle
- DWF :: Nexen Workflow (whoknowswhy)
- EARB:: Enterprise Architecture Review Board
- EDG :: Enterprise Document Gateway
- EFI :: Enterprise Federated Inbox (near MyTask)
- EGM :: Emergency General Meeting (of the stockholders)
- EMS :: Exception Management System
- ERI :: Enterprise Risk Management(?)
- ETF :: Exchange Trading Fund -  "an investment company whose shares are traded intraday on stock exchanges at market-determined prices"

- FA  :: Fund Accountant
- FAO :: Fund Accountant Officer(?)
- FASB:: Financial Accounting Standards Board, USA
- FIS :: <a new name for Sungard>
- FRS :: Financial Reporting Standard
- FX  :: (a foreign currency exchange)

- PD  :: Probability of Default
- PPE :: Property, Plant & Equipment

- SEC :: Securities and Exchange Comission

- RFP :: Request for Proposals


* Analysis of the Income Statement
  The income statement  (profit and loss (P&L) statement) looks at the expenses and revenues of an entity *over a period of time*, and shows whether or not the entity made a profit or loss over this period.

** Elements of

  | XYZ Corp                                 |   20X5 |   20X6 |
  |------------------------------------------+--------+--------|
  | Revenue (AKA Sales or Turnover)          |        |        |
  |------------------------------------------+--------+--------|
  | Widgets                                  | 12,375 | 12,990 |
  | Repair Kits                              |    429 |    330 |
  | Service                                  |  4,329 |  3,306 |
  | *Total Sales Revenue*                    | 17,133 | 16,626 |
  |                                          |        |        |
  |                                          |        |        |
  | Cost of Sales                            |        |        |
  |------------------------------------------+--------+--------|
  | Widgets                                  |  6,612 |  6,333 |
  | Repair Kits                              |     54 |     12 |
  | Service                                  |  3,567 |  2,841 |
  | *Total Sales Cost*                       | 10,233 |  9,186 |
  |                                          |        |        |
  | *Gross Profit (Loss) AKA Gross Income*   |  6,900 |  7,170 |
  |                                          |        |        |
  | Operating Expenses                       |        |        |
  |------------------------------------------+--------+--------|
  | General & Administrative                 |    876 |    903 |
  | Sales & Marketing                        |  4,167 |  4,242 |
  | Research & Development                   |    642 |    642 |
  | Other Operating Expenses                 |     15 |     21 |
  | *Total Operating Expenses*               |  5,700 |  5,808 |
  |                                          |        |        |
  | *Operating Income*                       |  1,200 |  1,362 |
  |                                          |        |        |
  | Interests Paid                           |      3 |      6 |
  | *Income Before Taxes*                    |  1,197 |  1,356 |
  |                                          |        |        |
  | Taxes                                    |    381 |    432 |
  | *Net Income from Continuing Operations*  |    816 |    924 |
  |                                          |        |        |
  | Exceptional Items (Non-Recurring Events) |      - |      3 |
  | *Net Income*                             |    816 |    924 |
  |                                          |        |        |
  | Dividends to Stockholders                |      0 |      6 |
  |------------------------------------------+--------+--------|
  | *Net Income Available to Shareholders*   |    816 |    915 |

Revenue (AKA Sales or Turnover) - amount derived from sale of goods or services involved in firm's ordinary activities after deducting trade discounts but before deduction of settlement discounts and addition of sales-based taxes.

Operating Expenses - can also include wages and salaries, light/heat, _depreciation_.

Dividend Cover: $\frac{Profits}{Total Dividends}$ - the higher the level of cover, the more secure the dividends are considered to be.

** Related Statements:
+ The Statement of Retained Earnings: $= Beginning Retained Earnings - Dividends Paid + Net Income$

+ The Statement of Total Recognized Gains and Losses: shows the extent to which shareholders' funds have increased or decreased from all gains and losses recognized in the period. The purpose of the statement is to highlight any items that, even if they were significant, would otherwise only appear in a note to the accounts, like:
  + a large foreign exchange rate variance (favorable or adverse) that might cause a large movement in reserves;
  + a large gain on the revaluation of a property
  + prior period adjustment (this will also appear on the income statement)

** Ratio Analysis
*** Profitabiity ratios
+ Gross profit margin $ = frac{Gross profit}{Sales revenue} * 100\% $

+ Net profit margin $ = frac{Net profit}{Sales revenue} * 100\% $
  (usually financing costs and interest income are excluded from Net profit as we're interested in the "normal" company operations).

+ Return on Capital Employed (ROCE): Capital Employed is shareholder's funds + Long-term borrowing (equals to Total accets less Current Liabilities). Meassures how effectively company is using its capital: $ROCE = frac{Earnings (profit) before interest and tax}{Total accets - Current liabilities} * 100\%$

*** Activity ratios
Show how well companyis managing its key short-term assets and liabilities (working capital):
+ Inventory turnover ratio $ = frac{Cost of sales}{Average inventory} $
+ Accounts Receivable Collection Period $ = frac{Average accounts receivable}/{Credit sales} * 365 $

also Accounts receivable turnover $ =frac{Credit sales}{Average accounts receivable} $

+ Accounts payable period $ = frac{Average accounts payable}{Cost of sales} * 365 $, also

Accounts payable turnover $ = frac{Cost of sales}{Average accounts payable} $
+ Asset turnover ratio $ = frac{Sales}{Average total assets} $.Shows how effectively a company's assets are being employed togenerate sales.

*** Investor's ratios
**** Earnings Per Share (EPS)
$ EPS = frac{Profit attributable to ordinary shareholders}{Weighted average number of ordinary shares in issue} $. Basically, it is amount ofprofit that belongs to asingle ordinary share. Companies are required to publish the statutory (AKA "basic") EPS. The "adjusted" EPS numbers are also popular; common adjustments are adding back goodwill, amortization and exceptional costs to profits. Also EPS can be differentiated accross time as:
+ Trailing EPS – last year's numbers and the only actual EPS
+ Current EPS – this year's numbers, which are still projections
+ Forward EPS – future (projected) earnings and share prices

**** Price Earning(P/E) Ratio
P/E Ratio $ = frac{Market price per ordinary share}{EPS} $. Gives an ideaof what market is willing to pay for company's earning. A higher P/E means that the same share of a company's profits will cost a prospective shareholder more. A higher P/E may reflect faster expected earnings growth, or lower risk earnings. Conversely, a low P/E may indicate a 'vote of no confidence' by the market or it could mean that the market has 'overlooked' the stock.


* Analysis of the Cash Flow Statement
** Overview
Cash flow types:
- Operating Activities: cash generated from internal business activities.
- Investing Activities: collection of money on load and buying/selling of long-term assets. Includes refurbishing menufacturing outlets to increase productivity and regularly servicing machinery to keep it in good condition.
- Financing Activities: cash flow to and from external sources, including money risen from selling stocks and bonds, and borrowing from banks.

** Uses of Cash Flow Statement
Can be used for:
- Determine corporate health
- Reconcile profit and cash
- Project future cash flow
- Assess the firm's liquidity

Working Capital to Sales $=frac{Inventory + Accounts Receivable - Account Payable}{Sales}$

** Limitations:

*** Reasons behind changes:
A CFS is a record of historical fact without any opinion. Thus, it may show:
- Expansion of inventory: without explanation was it because poor inventory or production control; inability to sell the finished product or deliberate act of policy;
- Increase in accounts receivable: may be because debtors are slow to pay, credit policy has changed or rise in receivables merely represents the expansion of sales;
- Raising new capital: do we really need it?

** Preparing a Cash Flow Statement
*** Direct Method

*** Indirect Method

** Interpreting the Cash Flow Statement

*** Ratios:
- Quality of Operation Income: $ = frac{Operating Cash Flow}{Operating Income} $
- Operating Cash Flow Ratio: $ = frac{Operating Cash Flow}{Current Liabilities} $
- Cash Flow to Asset Ratio: $ = frac{Operating Cash Flow}{Total Assets} $
- Cash Current Debt Coverage $ = frac{Opearting Cash Flow - Cash Dividends}{Current Interest - Bearing Debt}$
- Cash Flow Per Share (CPS) $ = frac{Operating Cash Flow}{Common Shares Outstanding} $

** Working Capital and Cash Flow

*** Managing Inventory
- Economic order quantity: EOQ model can be used to decide the optimum order quantity for inventory, which will minimize the cost of ordering and holding inventory
- Bulk purchase discount
- Buffer inventory

Inventory turnover $ = frac{Cost of sales}{Average inventory} $

*** Managing Cash



* DONE Bond Prces & Yields
  CLOSED: [2017-04-13 Thu 19:38]
Bond :: a debt security (issued by...). Generally makes a regular payment ("coupon") at fixed interval and a terminal payment ("face value", AKA "nominal value" or "maturity amount") on a known date (the "maturity date" or "redemption date").
- Details:
  - Price : "Par"
  - Amount (paid for the bond) : $100.000
  - Maturity (time to mature) : 5 years
  - Coupon payment : 6%

The current price for the bond inversely related to the payment (yield) currently available on the market.

** Bond Pricing
- The "Fair Price" of a bond: sum of the present values of all the future cash flows:

$ P = frac{c}{(1+r)}+ frac{c}{(1+r)^2} + ... + frac{c}{(1+r)^n} + frac{B}{(1+r)^n} = ... $

For semi-annual payments:

$ P = frac{c/2}{(1+r/2)}+ frac{c/2}{(1+r/2)^2} + ... + frac{c}{(1+r/2)^2n} + frac{B}{(1+r/2)^2n} = ... $

*** The Clean Price
is the fair price of the bond (that is, Present Value - PV) or the payment stream on the day after coupon payment. This is also a price which is quoted up until the next coupon paymnet.

*** The Dirty Price
is the price which is /actually paid/ - an clean price plus *accrued interest*:
Accrued Interest: the fraction of the *coupon payment* that the bond seller earns for holding the bond over the period of time between bond payments.

The inclusion of any interest accrued since the last payment period determines whether the bond is "dirty" or "clean". Bond prices quoted in press are usual the "clean" prices.

*** Valuation of Other Bond-Like Instruments
- Zero-Coupon Bonds (or zero): $ P = frac{cash inflow on the bond}{(1+r)^t} $
- Floating - rate notes (FRN): bonds with variable coupon payments. These bonds link the coupon payments to a measure of current market rates. I.e. the coupon rate might be linked to T-bill rate plus 2.5%.

** Bond Yields
*** Yield To Maturity (YTM) or  Redemption Yield
the single rate of interest that equates the present value of the income stream with the current price (same as Internal Rate or Return, IRR): the approximate total return anticipated on a bond if the bond is held until the end of its lifetime and all coupon payments were invested at that rate. Often is being calculated via "trials and errors" method.

The YTM of a zero-coupon bond is referred to as the *spot yield* - also a measure of the interest rate that is appropriate for discounting a single payment ini future.

*** Current Yield (AKA Flat Yield or Interest Yield)
The current Yield is a coupon expressed as a percentage of the current price. For example, if the annual coupon on a bond is 7% and the bond price is 102%, then the current yield is 6.86% = 7% / 102%

*** Holding Period Yield
= the return from holding a bond for a fixed period

*** The Forward Yield
= the future rate of interest that is implied by spot yields for different maturities. For instanse:
- one-year spot yiled R1 = 10%
- two-year spot yield R2 = 12%
then the implied one-year spot rate in one year's time is:
$ Rf = frac{(1+R2)^2}{(1+R1)} - 1 = frac{1.12^2}{1.1} - 1 = 14.04% $

** Bond Rates of Return (RoR)


Imagine you buy a bond which pays a 8% coupon for $1070 and sell in one year for $1190. Total return of investment is the coupon payment ($80) plus price difference ($1,190-$1,070 = $120). Therefore, the rate of return (RoR) is:
$ ROR = frac{Coupon + Capital Gain}{Investment} =$200/$1070 =18.69% $

The ROR on a bond is linked to market interest rates (bond price decrease when market interest rate increase and vice versa) => bonds are subject of *market interest risk*.

** Theories of the Term Structure of Interest Rates

There are three main theories as to why spot rates vary by maturity:
- Expectation Hypothesis
The T-period spot rate is just the average of the expected one-period spot rate over the next T periods. The ter structure can be upward or downward sloping depending on expectations of future short-term interest rates.

- Liquidity Hypothesis
Even if the short-term interest rates are not expected to change, the term structure should be upward sloping. This is because there is more real interest rate risk for long-term bonds than for short-term bills.

- Seqmented Markes Hypothesis
The investors who buy short-term bonds are different from those that buy long-term bonds. The shape of the term structure is then determined by supply and demand amongst each type of investor.


* DONE Options
  CLOSED: [2017-04-13 Thu 19:38]
** Specification:
On June 1 Harry pays Sally $200 ($2 per share) for an option that gives him right to buy 100 shares of Widgetcorp stock from Sally at a price of $50 on September 1:
- Option Holder :: Harry
- Option Writer :: Sally
- Start Date :: June 1
- Expiration Date :: September 1
- Premium :: $200
- Underlying Asset :: Widgetcorp stock
- Quantity :: 100
- Option Type :: call (right to purchase). If it was right to sell, it would be *put* type. Sally sold (*short*) the call, Harry bought (*long*) one.
- Excercise/Strike Price :: $50

** Moneyness:
(for the above example):
- in-the-money (ITM) :: Spot Price > Strike Price (Harry can excercise option and buy shares from Sally; than he can keep or sell at the higher price)
- at-the-money (ATM) :: Spot Price = Strike Price (Harry should be indifferent between excercising the option or buying shares at the market)
- out-of-the-money (OTM) :: Spot Price < Strike Price (Harry can let the option expire and buy the shares at the open market cheaply)

** Excercise:
- Physical Settlement :: Harry pays $5000 and gets shares;
- Cash Settlement :: a payment is made based on the difference between the strike and the market (spot) price.

** Style:
- European-style :: has a single excercise date when the holder must decide if he wants to excercise the option;
- American-style :: excercise may take place at any time between the start date and expiration date;
- Bermudan :: exercise is restricted to a predetermined set of dates or times between the start date and the expiration date. For instance, a 3-month Bermudan call option on a stock might allow the holder to exercise the option during the first business hour of any Wednesday.

** Uses:

*** Protective Put
Holding something (security X); want to protect ourselves vs major price fall. Buy a put option on the security X at a strike price P which we srill can withstand. In worst case (market price falls below P) our loss is (Current Price - P + Premium), but never greater;

*** Procective Call
Protecting yourself from rising prices: "For example, an airline’s revenues may fall in the event of rising fuel prices. The airline can protect itself in a similar fashion to the previous example, but by buying a call option rather than a put. The strike price sets a ceiling on fuel costs – if, at expiration, the fuel price is lower than the strike, then the airline simply lets the option expire worthless and buys its fuel at the cheaper market price."

*** Covered Call
Generating cash by selling options against their positions: "Let’s look at Harry and his Widgetcorp portfolio again. Even though he is a long-term holder of the stock, assume that he might be willing to sell shares if the price increased (in the short term) above a particular target level. He can monetize this view by selling call options struck at this target price. If, as he expects, the price stays below the strike, the option premium earned increases the value of his portfolio. If the price “pops” above this level, he can sell his portfolio at the target price".

*** Covered Put
"For an airline looking to protect itself against rising fuel prices, the situation would be reversed. It would sell a put option allowing market participants to sell fuel to the airline in the event that fuel prices dropped below a particular target level";

*** Combinations
- Collar :: financing insurance (buying a put) by selling a call.
- Straddle :: a combination of a call and a put with the same strike price and expiration date. Assuming the expiration price is not equal to the strike price, then irrespective of the level of the underlying at expiration, this combination will have some value:
- If the expiration price is below the strike price, then the put has value and the call expires worthless.
- If the expiration price is above the strike price, then the call has value and the put expires worthless.

Since one of the options will be in-the-money, the value of a straddle must be positive at expiration. But for a straddle to be profitable, the payoff of the positive leg must be greater than the total premium paid. The price of a straddle gives an indication of the /size/ of expected market movements (volatility) rather than the /direction/.
Comment: "Straddles are ideal for option dealers. For example, a dealer who sells puts and calls in the same quantities may be able to (broadly speaking) balance out market risk. But the dealer will still be exposed to the volatility risk – market movements may be greater than anticipated and the payoffs on the sold options may exceed earned premiums. This risk could be mitigated by buying straddles".

** Complex Options
- Multiple Excercise Date and/or Strike Price :: "In some cases, different exercise dates may also have different expiration prices. For example, a call option with three exercise dates might have ascending strike prices for each date";
- Path-Dependency :: the expiration value is dependent on previous observations of the underlying asset price; For example:
-- barrier options (“knock-outs” and “kick-ins/knock-ins”) are a class of option where exercise is dependent on whether certain price levels have been reached in particular periods in the future;
-- asian option : the (cash-settled) payoff is based on the difference between the strike price and the average price (measured over some period before expiration).
- Digital (binary) options :: (also "bet" options): the payoff is fixed and based on cash settlement. For example, a digital call might have a fixed payoff of USD 10 if a particular asset price exceeded USD 100 at expiration. It would not matter if the expiration price was USD 100.01 or USD 1000 – the USD 10 payoff would be the same.
- Multi-Asset Option :: An option may have more than one underlying asset. For instance, the exercise of an option on one asset might be contingent on the market price of another. There are also equity options that reference baskets containing many underlying stocks, with payoffs linked (for example) to the best or worse performing stocks.


* Equities – Trading

** Overview

Alpha :: a risk-adjusted measure of the 'excess return' on an investment over and above a benchmark index of 'risk-free' investment. Positive alpha figure indicates that a stock has performed better than its beta would predict. A negative alpha means indicates that a stock has underperformed.
Beta :: measures the sensivity of a stock's price to changes in the market.
STP :: Straight Through Processing. The details of individual trade are inputted only once following trade execution.
FIX :: Financial Information Exchange protocol (messaging - based).
OMS :: Order Management System
Crossing Networks :: electronic systems set up by brokers to bring together potential buyers and sellers for the purpose of trading large blocks of securities. Some Crossing Networks are even registered as alternative trading systems.

** Information & Models

Public Data: company information, economic indicators, macro & micro information

Whisper Number :: unofficial estimate of Earnings Per Share (EPS)

- Market Information:
-- Spread :: difference between the bid and ask (offer) price. Represent some measure of risk: when spread suddenly change, it is an indication of market perception of increased risk.
-- Size :: another measure of risk. In a sense, there is a tradeoff between size and spread.
-- Volume :: number of shares traded in a stock for a given period (usually a day).
ADV :: Average Day Volume.
-- Volatility :: measure of the riskness of:
--- holding the stock;
--- trading a stock.
Volatility measure is called Beta. Beta > 1 means the stock is more volatile than a market; < 1 - less volatile.

*** Models:
- Pricing Models: intended to produce a _fair price_ for the stock;
- Portfolio Models
- Risk Management Models
VAR :: Value At Risk
- "Black Box" models: algorithms that use immediately market information to make trades (?)

Because they are based on assumptions, models are always a simplified representation of what happens under real-life conditions. If these assumptions break down, as they can do particularly under extreme market conditions, then the model is rendered virtually worthless. Model risk can be defined as the risk of loss arising from the failure of a model to sufficiently match reality, or to otherwise deliver the required results. It can arise from a number of issues, including:
- invalid assumptions (for instance, assuming a lognormal distribution when the true distribution is 'fat-tailed')
- mathematical errors (for example, in determining the formulas for valuing more complex financial instruments)
- inappropriate parameter specification
- the lack of transparent market prices for some of the more illiquid securities
- errors in implementation ('implementation risk')
- poor or inappropriate data ('garbage in, garbage out')

** Trade Execution & Transaction Costs

Costs:
- Explicit (comissions, custodial fees, transfer fees, stamp duties)
- Implicit (indirect): bid-ask spread, market impact costs, execution cost (reflect the difference between the transaction price and what the market price would have been in the absence of that transaction), opportunity cost (Intended/Unintended),


* DONE Algorithmic Trading
  CLOSED: [2017-04-13 Thu 19:38]
** The Strategies
Key Parameters:
- Price
- Size & Liquidity
- Timing
- Fill Ratio (the likelihood that an order will be executed/completed)
- Transaction Costs

** The Tasks Performed
- Data Analysis
- Decision Analysis
- Trade Matching
- Trade Execution
- Smart Order Routing (SOR)

** Types of Algorithms
- Impact-driven algorithms:
-- Volume Weighted Average Price - VWAP
-- Time Weighted Average Price-TWAP strategy
-- Sensivity - SENS strategy
-- Percent of Volume (POV) strategy

- Cost-driven algorithms - trying to reduce the effect of overall transaction costs, like market impact:
-- Implementation Shortfall (IS)
-- Market Close (MC)

- Opportunistic algorithms
-- Price Inline (PI)
-- Liquidity - Driven (LD)
-- Pairs Trading (PT) : used for statistical arbitrage.

- Others:
-- Arrival Price (AP)
-- Target Volume (TVOL)

** Risks and Concerns


* High-Frequency Trading (HFT)

** Introduction
Types of HFT firms:
- Independent and proprietary market-makers
- Broker-dealer proprietary desks at major investment houses
- Hedge funds using quantitative trading algorithms

Flash Orders: "a very controversial practice" by several ATSs is the offering of 'flash orders' to a number of HFT firms. In some marketplaces, it is possible for HTFs to get s sneak preview of orders for a fraction of a second before they are sent to the market for everyone to view (in exchange for a fee).

*** Positive impact on the market:
- increased liquidity;
- narrowing of bid-ask spread through increased competition;
- improved market efficiency due to prices reflecting information more accurately and rapidly.

** Key HFT Strategies
*** Liquidity Provision
- Market-making
- Rebate Trading

*** Technical Trading
- Statistical Arbitrage
i.e. the mean-reversion strategy, where underlying asset (such as a stock price) will tend to move back towards the average (mean) value over time.
- Pairs Trading

** Development of IT




* Relative Value (RV) Trading


* Forwards and Futures - An Introduction
Futures transactions are executed on either a bilateral OTC basis or on standardized futures exchanges. Historically there have been many differences between these markets in terms of product descriptions and credit arrangements. However, in recent years the distinctions between these markets have broken down. Some of the market reforms see OTC derivatives now being cleared by the same clearing houses as exchange-traded contracts.

** Similarities Between Forwards and Futures
*** Spot & Future Prices
- Spot Price: the price at which an asset is bought or sold for immediate delivery/settlement.
- Forward Contract: a privately negotiated contract between two parties, who agree to exchange a financial transaction (typically an asset) for a specified price at an agreed date in the future. The contract states who is agreeing to buy and sell the asset, for what price, and for when. This has the effect of fixing the price for both parties, so that they are both unaffected by any price volatility.
- Futures Contract: much like a Forward except that the terms of the agreement aren't privately customized. The terms are standardized and the contracts are traded in on a regulated exchange. Although the trade may have been initiated between the two parties, their contracts are typically novated by the exchange. This means that the counterparty for each of the parties now becomes the exchange. The parties will be required to settle the gains and losses on each contract daily. Each futures contract defines a standard size, delivery date, quality, minimum price fluctuation, and so on.

*** Elements of Forwards and Futures Contracts
Forwards and futures are fundamentally the same derivative. A forward or future is a legally binding agreement made today (trade date) to deliver/receive something (underlying asset and quantity) on a future date (delivery date) at a price that is agreed upon today by both market participants (agreed price).

- Trade Date: the date the transaction is agreed. For forwards, this is the date of entry into the forward agreement, and for futures, it is the date that the contract was bought or sold.
- Underlying Asset and Quantity: are outlined in the forward/futures contract. The grade or quality of the asset can also be set out. For example, a contract could be for five thousand barrels of light sweet crude oil.
- Delivery Date: for forwards, the delivery date is the future date that the actual transaction will occur. In other words, it is the date the contract is settled. The delivery date is individually negotiated for each transaction. Futures contracts have standardized delivery dates such as every month or every three months. The Dow Jones Eurostoxx 50 futures index, a stock index of 50 of the largest eurozone stocks by market capitalization, has a standard contract settlement of four times a year, in March, June, September, and December.
- Agreed Price: the effective price that will be paid by one party to a counterparty when the delivery of the underlying asset is made.

*** Standardized Settlement
The means by which delivery will be made in a forward or futures contract will be outlined in the contract:
- Physical settlement involves the actual physical delivery of the underlying transaction/asset on reaching the settlement date. The delivery details on the contract will specify particular settlement venues (warehouses, pipelines, and so on) and any invoicing procedures. For instance, the New York Mercantile Exchange (NYMEX) lists a contract for crude oil which has a physical settlement for one thousand barrels of crude oil to be delivered to a key pipeline hub in Oklahoma.

- Cash Settlement: the amount of cash to be exchanged at settlement will be equal to the difference between the prevailing market price and the prespecified contract price. Generally contracts are cash settled either because it is more convenient to cash settle the contract or physical delivery of the underlying asset is not possible.

** Difference Between Forwards and Futures
Can be grouped as follows:
-Marketplace:
-- OTC market: Forward contracts are traded via the broker-dealer network. A broker-dealer contacts another broker-dealer by telephone or computer network and the two dealers agree on the specific details.
-- Recognized derivatives exchange: Futures contracts are traded on recognized exchanges. A trader would be dealing on a similar market price to the one other traders deal on and the details of the underlying contract would be the same across all comparable contracts.
- Bridging the Marketplace Gap: it may not be easy to make a distinction between an OTC and an exchange-traded transaction. In addition to the fact that most market participants may execute similar transactions in both areas, there is often an "official" bridge between them.
- Customization
- Contract Standardization: forward contracts are privately negotiated between the two parties involved in the contract, and between them they can customize the contract to their needs. This is not the case with futures contracts. Particular elements are standardized by the exchanges and listed in the contract specification:
-- Settlement Dates: futures contracts have standardized settlement dates during particular delivery months. Settlement takes place on a predetermined date during that month (usually around the middle of the month). Exchanges list multiple delivery months for a particular product depending on demand.
-- Underlying Transaction: each futures contract references a fixed quantity of a specific underlying asset or contract. For example, each CME/NYMEX gold futures contract has an underlying quantity of 100 ounces of gold, satisfying particular quality criteria.
-- Standardized Pricing: prices are usually quoted relative to the basic measurement for an asset. For example, although the gold futures contract has an underlying quantity of 100 ounces, the contract price is “dollars per ounce.” There will be a minimum price fluctuation (tick size) set at a size small enough to ensure granularity, but not so small that liquidity is unduly dissipated. In the case of the gold futures contract, the tick size is USD 0.10. Contracts have a tick value equal to the tick size multiplied by the size of the underlying. For example, in the gold futures contract, the tick value = USD 0.10 × 100 ounces = USD 10.
-- Contract Specification: there is a contract specification for each futures contract with regards to the underlying asset, trading times, trading fluctuations, and so on. The underlying forward transaction is thus standardized and becomes a fungible entity (capable of being freely transferred). This transferability gives liquidity to futures markets.

*** Unwinding a Contract
The fungible nature of futures contracts enhances their liquidity. There will be a large number of market participants with positions (long or short) in the same standardized instruments. Each futures contract on that exchange has the same counterparty (the exchange itself or an appointed clearing house). If a market participant wishes to dissolve a position ahead of maturity, there is no need to go back to the original counterparty – the participant can simply sell the contract in the market if it is a long position (or buy if short position). The extinguished position is then cash-settled, without any requirement for a new instrument.

** Risks in the Forwards and Futures Markets
- Risk Types
 -- Credit Risk: credit risk is the risk that a party to a financial transaction will not be able to make scheduled payments in line with its legal obligations. Calculating the amount of credit exposure is a particularly complex task as it involves calculating the probability of default, the amount lost in the event of default, and the fair compensation to be paid to the counterparty.
  --- Margin: the clearing house insulates itself from the default risk of participants by requiring them to keep a margin account above a predetermined level (the maintenance margin).
  --- Blateral Collateralization Agreements: specified the collateral required to offset potential losses caused by counterparty defaults. Similar to variation margin, collateral amounts are revised periodically in accordance with market movements.
 -- Basis Risk: basis is the price difference between the current forward price of the underlying transaction (for example, a government bond) and the delivery price of that transaction: $Basis = Futures Price – Spot Price$. Basis risk is the chance that the basis will have strengthened or weakened from the time the hedge is implemented to the time when the hedge is removed.
 -- Liquidity Risk can be defined as the risk of an asset holder not being able to sell that asset quickly enough to prevent or minimize a loss. Liquidity risk has two dimensions:
  --- The ability to refinance
  --- The ability to sell assets at a reasonable price

** Trading Mechanisms and Regulations
*** Central Cleaning
Following the financial crisis, regulators worldwide turned their attention to OTC counterparty credit risk. In both Europe and the US, legislation dictates that "standardized" OTC derivatives must be cleared through a "central clearing counterparty (CCP)." Under this clearing arrangement, market participants replace their original dealing counterparties with a single CCP. Collateral payments are made to and from the CCP, allowing market participants to net offsetting payments.


* Bond Futures Basis

* Basis Trading
A tool for enchancing yield, the simultaneous trading of futures contracts written on government bonds and the bonds themselves. For this to work the portfolio manager must have a view on the relationshio between futures prices between cach bond prices. Three possible views possible:

1. Spot bond prices will move away fromfutures prices.
2. No changes in the differential between spot bond prices and futures prices (AKA Gross Basis).
3. Spot bond prices will move towards the futures prices.

* Options: Beyond Black-Scholes
